# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        self.txtDatos = QtWidgets.QLineEdit(Form)
        self.txtDatos.setGeometry(QtCore.QRect(150, 40, 291, 22))
        self.txtDatos.setObjectName("txtDatos")

        self.btnEnviar = QtWidgets.QPushButton(Form)
        self.btnEnviar.setGeometry(QtCore.QRect(250, 70, 93, 28))
        self.btnEnviar.setObjectName("btnEnviar")

        self.lblS1 = QtWidgets.QLabel(Form)
        self.lblS1.setGeometry(QtCore.QRect(200, 110, 200, 50))
        self.lblS1.setText("")
        self.lblS1.setObjectName("lblS1")

        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(540, 180, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.txtPuerto = QtWidgets.QLineEdit(Form)
        self.txtPuerto.setGeometry(QtCore.QRect(530, 150, 113, 22))
        self.txtPuerto.setObjectName("txtPuerto")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnEnviar.setText(_translate("Form", "Enviar"))
        self.pushButton.setText(_translate("Form", "Conectar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
